version: "3.8"
name: evastore
services:
    database:
        container_name: database
        image: postgres:16.0-alpine
        restart: always
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_PORT=${DATABASE_PORT}
        volumes:
            - ./database:/var/lib/postgresql/data
        ports:
          - ${DATABASE_PORT}:${DATABASE_PORT}
